import type { ZodType } from 'zod';
import type { Reading,Interpretation,SpreadId } from '@star-oracle/domain';
export type CreateReadingInput={kind:'tarot'|'iching';question:string;spread:SpreadId;allowReversed:boolean;requestId:string;scenario:string;method:'coins'|'numbers'|'time';numbers?:[number,number,number];time?:string};
export type JournalData={note:string;mood:'calm'|'hopeful'|'tired'|'restless'|'low'|null;version:number};
export const CreateReading:ZodType<CreateReadingInput>;
export const JournalInput:ZodType<JournalData>;
export const ShareInput:ZodType<{shared:boolean}>;
export const AIInput:ZodType<{consent:true;requestId?:string}>;
export const UserStatus:ZodType<{disabled:boolean}>;
export const PageQuery:ZodType<{cursor?:string;limit:number}>;
export type ReadingRecord={id:string;reading:Reading;interpretation:Interpretation;ai:boolean;shared:boolean;createdAt:string;favorite?:boolean;tags?:string[];note?:string;metadataVersion?:number};
export type DailyRecord={id:string;date:string;reading:Reading;journal:JournalData;message:{title:string;text:string;action:string;reflection:string}};
export type CurrentUser={id:string;name:string;email:string;role:'user'|'admin';twoFactorEnabled:boolean};
export const DailyQuery:ZodType<{cursor?:string;limit:number}>;
export const AdminPageQuery:ZodType<{cursor?:string;limit:number}>;
export type ReadingQueryInput={cursor?:string;limit:number;q?:string;kind?:'tarot'|'iching';favorite?:boolean;tag?:string;dateFrom?:string;dateTo?:string};
export const ReadingQuery:ZodType<ReadingQueryInput>;
export type ReadingMetadataInput={favorite:boolean;tags:string[];note:string;version:number};
export const ReadingMetadata:ZodType<ReadingMetadataInput>;
export type ConversationInputData={prompt:string;consent:true;requestId:string};
export const ConversationInput:ZodType<ConversationInputData>;
export type ConversationTurn={id:string;prompt:string;answer:Interpretation|null;status:'pending'|'done'|'failed';createdAt:string};
export type ActionRecord={id:string;title:string;detail:string;readingId:string|null;dueDate:string|null;completedAt:string|null;version:number;createdAt:string;updatedAt:string};
export type MembershipRecord={tier:'free'|'plus';expiresAt:string|null;credits:number;dailyLimit:number;usedToday:number;remainingToday:number;paymentEnabled:false};
