// Adapted from Xuandu (MIT), copyright (c) 2026 cnc876297794-arch.
// Full notice: licenses/xuandu-MIT.txt. Symbolic meanings, not classical quotations.
const MAJOR_ARCANA = [
  {
    id: "major-fool",
    arcana: "major",
    number: 0,
    name: "愚者",
    en: "The Fool",
    mark: "0",
    upright: ["新起点", "信任", "自发"],
    reversed: ["鲁莽", "逃避", "天真"],
  },
  {
    id: "major-magician",
    arcana: "major",
    number: 1,
    name: "魔术师",
    en: "The Magician",
    mark: "I",
    upright: ["主动", "技能", "实现"],
    reversed: ["操纵", "分散", "才华未用"],
  },
  {
    id: "major-priestess",
    arcana: "major",
    number: 2,
    name: "女祭司",
    en: "The High Priestess",
    mark: "II",
    upright: ["直觉", "静默", "内知"],
    reversed: ["隔绝直觉", "隐情", "困惑"],
  },
  {
    id: "major-empress",
    arcana: "major",
    number: 3,
    name: "皇后",
    en: "The Empress",
    mark: "III",
    upright: ["滋养", "丰盛", "创造"],
    reversed: ["过度付出", "停滞", "依赖"],
  },
  {
    id: "major-emperor",
    arcana: "major",
    number: 4,
    name: "皇帝",
    en: "The Emperor",
    mark: "IV",
    upright: ["结构", "权威", "边界"],
    reversed: ["僵化", "控制", "秩序薄弱"],
  },
  {
    id: "major-hierophant",
    arcana: "major",
    number: 5,
    name: "教皇",
    en: "The Hierophant",
    mark: "V",
    upright: ["传统", "学习", "制度"],
    reversed: ["教条", "质疑规则", "非从众"],
  },
  {
    id: "major-lovers",
    arcana: "major",
    number: 6,
    name: "恋人",
    en: "The Lovers",
    mark: "VI",
    upright: ["选择", "一致", "关系"],
    reversed: ["失衡", "犹疑", "疏离"],
  },
  {
    id: "major-chariot",
    arcana: "major",
    number: 7,
    name: "战车",
    en: "The Chariot",
    mark: "VII",
    upright: ["方向", "意志", "推进"],
    reversed: ["失控", "逞强", "停滞"],
  },
  {
    id: "major-strength",
    arcana: "major",
    number: 8,
    name: "力量",
    en: "Strength",
    mark: "VIII",
    upright: ["勇气", "耐心", "柔韧力量"],
    reversed: ["自疑", "强迫", "耗竭"],
  },
  {
    id: "major-hermit",
    arcana: "major",
    number: 9,
    name: "隐者",
    en: "The Hermit",
    mark: "IX",
    upright: ["内省", "智慧", "独处"],
    reversed: ["隔离", "回避", "孤独"],
  },
  {
    id: "major-wheel",
    arcana: "major",
    number: 10,
    name: "命运之轮",
    en: "Wheel of Fortune",
    mark: "X",
    upright: ["周期", "变化", "机会"],
    reversed: ["抗拒变化", "延迟", "反复"],
  },
  {
    id: "major-justice",
    arcana: "major",
    number: 11,
    name: "正义",
    en: "Justice",
    mark: "XI",
    upright: ["公平", "真相", "责任"],
    reversed: ["偏见", "逃责", "不公"],
  },
  {
    id: "major-hanged-man",
    arcana: "major",
    number: 12,
    name: "倒吊人",
    en: "The Hanged Man",
    mark: "XII",
    upright: ["暂停", "换视角", "放下"],
    reversed: ["拖延", "抗拒", "无谓牺牲"],
  },
  {
    id: "major-death",
    arcana: "major",
    number: 13,
    name: "死神",
    en: "Death",
    mark: "XIII",
    upright: ["结束", "过渡", "更新"],
    reversed: ["执着", "惧变", "僵滞"],
  },
  {
    id: "major-temperance",
    arcana: "major",
    number: 14,
    name: "节制",
    en: "Temperance",
    mark: "XIV",
    upright: ["平衡", "整合", "节制"],
    reversed: ["过量", "失衡", "急躁"],
  },
  {
    id: "major-devil",
    arcana: "major",
    number: 15,
    name: "恶魔",
    en: "The Devil",
    mark: "XV",
    upright: ["依附", "欲望", "阴影"],
    reversed: ["松绑", "觉察", "夺回选择"],
  },
  {
    id: "major-tower",
    arcana: "major",
    number: 16,
    name: "高塔",
    en: "The Tower",
    mark: "XVI",
    upright: ["剧变", "揭露", "解放"],
    reversed: ["延后危机", "恐惧", "回避"],
  },
  {
    id: "major-star",
    arcana: "major",
    number: 17,
    name: "星星",
    en: "The Star",
    mark: "XVII",
    upright: ["希望", "疗愈", "启发"],
    reversed: ["灰心", "失联", "怀疑"],
  },
  {
    id: "major-moon",
    arcana: "major",
    number: 18,
    name: "月亮",
    en: "The Moon",
    mark: "XVIII",
    upright: ["不确定", "梦", "直觉"],
    reversed: ["迷雾渐散", "否认", "焦虑"],
  },
  {
    id: "major-sun",
    arcana: "major",
    number: 19,
    name: "太阳",
    en: "The Sun",
    mark: "XIX",
    upright: ["清晰", "喜悦", "活力"],
    reversed: ["喜悦受抑", "曝光过度", "延迟"],
  },
  {
    id: "major-judgement",
    arcana: "major",
    number: 20,
    name: "审判",
    en: "Judgement",
    mark: "XX",
    upright: ["觉醒", "复盘", "召唤"],
    reversed: ["自疑", "回避", "苛责"],
  },
  {
    id: "major-world",
    arcana: "major",
    number: 21,
    name: "世界",
    en: "The World",
    mark: "XXI",
    upright: ["完成", "整合", "归属"],
    reversed: ["未竟", "欠收尾", "视野受限"],
  },
];

const SUITS = [
  {
    id: "wands",
    name: "权杖",
    en: "Wands",
    mark: "✦",
    theme: "行动、创造与意志",
    shadow: "冲动、耗散或失去方向",
  },
  {
    id: "cups",
    name: "圣杯",
    en: "Cups",
    mark: "◡",
    theme: "情感、关系与直觉",
    shadow: "情绪淹没、依赖或回避感受",
  },
  {
    id: "swords",
    name: "宝剑",
    en: "Swords",
    mark: "†",
    theme: "思想、沟通与冲突",
    shadow: "过度分析、言语伤害或内耗",
  },
  {
    id: "pentacles",
    name: "星币",
    en: "Pentacles",
    mark: "⟡",
    theme: "资源、身体、工作与物质",
    shadow: "匮乏焦虑、固着或忽略身心",
  },
];

const RANKS = [
  { id: "ace", name: "王牌", en: "Ace", mark: "A", stage: "开端与潜能", reverse: "起步受阻或能量未被使用" },
  { id: "2", name: "二", en: "Two", mark: "II", stage: "权衡与配对", reverse: "摇摆、失衡或选择延迟" },
  { id: "3", name: "三", en: "Three", mark: "III", stage: "发展与协作", reverse: "协作断裂或成长不均" },
  { id: "4", name: "四", en: "Four", mark: "IV", stage: "稳定与边界", reverse: "僵住、封闭或基础松动" },
  { id: "5", name: "五", en: "Five", mark: "V", stage: "摩擦与调整", reverse: "冲突内化或开始修复" },
  { id: "6", name: "六", en: "Six", mark: "VI", stage: "交流与重新平衡", reverse: "交换失衡或旧账未清" },
  { id: "7", name: "七", en: "Seven", mark: "VII", stage: "评估与坚持", reverse: "分心、防御或策略失效" },
  { id: "8", name: "八", en: "Eight", mark: "VIII", stage: "推进与练习", reverse: "停滞、急进或重复无效动作" },
  { id: "9", name: "九", en: "Nine", mark: "IX", stage: "成熟与临界", reverse: "疲惫、过量或差最后一步" },
  { id: "10", name: "十", en: "Ten", mark: "X", stage: "完成、结果与负担", reverse: "难以收尾或开始卸下负担" },
  { id: "page", name: "侍从", en: "Page", mark: "P", stage: "学习、消息与初次尝试", reverse: "消息失真、经验不足或不肯学习" },
  { id: "knight", name: "骑士", en: "Knight", mark: "N", stage: "追求、移动与投入", reverse: "冒进、停摆或目标反复" },
  { id: "queen", name: "王后", en: "Queen", mark: "Q", stage: "内在掌握、承接与滋养", reverse: "过度内化、情绪耗竭或掌控" },
  { id: "king", name: "国王", en: "King", mark: "K", stage: "外在管理、成熟与责任", reverse: "滥用权力、僵化或逃避责任" },
];

const MINOR_ARCANA = SUITS.flatMap((suit) =>
  RANKS.map((rank) => ({
    id: `${suit.id}-${rank.id}`,
    arcana: "minor",
    suit: suit.id,
    rank: rank.id,
    name: `${suit.name}${rank.name}`,
    en: `${rank.en} of ${suit.en}`,
    mark: `${rank.mark}${suit.mark}`,
    upright: [rank.stage, suit.theme],
    reversed: [rank.reverse, suit.shadow],
  })),
);

export const TAROT_DECK = [...MAJOR_ARCANA, ...MINOR_ARCANA];


export const KING_WEN_BY_MASK = [
  2, 24, 7, 19, 15, 36, 46, 11, 16, 51, 40, 54, 62, 55, 32, 34, 8, 3,
  29, 60, 39, 63, 48, 5, 45, 17, 47, 58, 31, 49, 28, 43, 23, 27, 4, 41,
  52, 22, 18, 26, 35, 21, 64, 38, 56, 30, 50, 14, 20, 42, 59, 61, 53,
  37, 57, 9, 12, 25, 6, 10, 33, 13, 44, 1,
];

export const KING_WEN_NAMES = [
  "",
  "乾",
  "坤",
  "屯",
  "蒙",
  "需",
  "讼",
  "师",
  "比",
  "小畜",
  "履",
  "泰",
  "否",
  "同人",
  "大有",
  "谦",
  "豫",
  "随",
  "蛊",
  "临",
  "观",
  "噬嗑",
  "贲",
  "剥",
  "复",
  "无妄",
  "大畜",
  "颐",
  "大过",
  "坎",
  "离",
  "咸",
  "恒",
  "遯",
  "大壮",
  "晋",
  "明夷",
  "家人",
  "睽",
  "蹇",
  "解",
  "损",
  "益",
  "夬",
  "姤",
  "萃",
  "升",
  "困",
  "井",
  "革",
  "鼎",
  "震",
  "艮",
  "渐",
  "归妹",
  "丰",
  "旅",
  "巽",
  "兑",
  "涣",
  "节",
  "中孚",
  "小过",
  "既济",
  "未济",
];

const REFLECTIONS = [
  ["", ""],
  ["创造与健行", "主动之后，怎样以自律避免刚强过度？"],
  ["承载与顺势", "此刻有什么更适合滋养，而不是催促？"],
  ["开端之难", "新事物尚未成形，先稳住哪一个支点？"],
  ["启蒙与求问", "承认未知之后，最值得请教的问题是什么？"],
  ["等待与准备", "等待期间可以补足什么条件？"],
  ["争议与边界", "哪些分歧值得澄清，哪些争执应当止步？"],
  ["组织与纪律", "如何让共同目标、角色与边界更清楚？"],
  ["亲近与结盟", "你愿意与谁建立基于信任的合作？"],
  ["小步积蓄", "还差哪一点耐心，才能让力量真正聚拢？"],
  ["谨慎履行", "身处敏感局面时，怎样既诚实又守礼？"],
  ["通达与交融", "上下相通之时，怎样让好循环持续？"],
  ["闭塞与保全", "外部不通时，哪些内在原则仍需守住？"],
  ["求同与协作", "共同点是什么，差异又该如何被容纳？"],
  ["丰有与分享", "资源充足时，怎样使用才不失其正？"],
  ["谦逊与留白", "降低姿态会为谁、为何事腾出空间？"],
  ["顺势而动", "热情已起，如何以准备和节度承接？"],
  ["随时与适变", "顺应变化时，哪些核心不应随波改变？"],
  ["整治旧弊", "问题的根源在哪里，先修复哪一环？"],
  ["临近与担当", "机会靠近时，如何亲自到场并持续照看？"],
  ["观察与示范", "先看清全局，再决定要用什么行动示范？"],
  ["决断与疏通", "什么阻碍需要被清楚处理，而不是绕开？"],
  ["修饰与实质", "形式能服务内容到什么程度？"],
  ["剥落与止损", "当结构松动时，什么需要先被保护？"],
  ["回返与复苏", "哪一个微小但真实的信号正在回来？"],
  ["真诚与不妄", "若不靠预设和侥幸，你会怎样回应？"],
  ["蓄力与学习", "力量增长之前，还需驯服什么冲动？"],
  ["滋养与言语", "你正在摄入什么，也正在喂养什么？"],
  ["承载过重", "哪根支梁已经超负荷，需要重新分配？"],
  ["险中求通", "反复出现的困难正在训练哪种能力？"],
  ["明辨与依附", "什么值得照亮，什么需要合适的依托？"],
  ["感应与互惠", "真正的影响来自吸引、倾听还是控制？"],
  ["恒久与节律", "什么做法经得起时间，也容得下调整？"],
  ["退守与保存", "后退一步是逃避，还是为了保全方向？"],
  ["强盛与节制", "力量充足时，怎样避免越界？"],
  ["进展与显明", "被看见之后，如何继续稳健推进？"],
  ["晦明与韬光", "环境不利时，怎样保护内在的清明？"],
  ["家道与分工", "亲近关系中的角色、规则是否需要重订？"],
  ["分歧与求异", "不同立场之间，有没有仍可合作的部分？"],
  ["阻难与转身", "正面难行时，哪个方向值得重新评估？"],
  ["松解与释放", "危机缓和后，什么旧结可以真正解开？"],
  ["减省与聚焦", "减去什么，反而能保护更重要的东西？"],
  ["增益与共好", "增加资源时，谁也应当从中受益？"],
  ["决口与公开", "该说清楚的事，怎样坚定而不粗暴地说？"],
  ["相遇与警觉", "突然出现的力量值得欢迎，还是需要边界？"],
  ["汇聚与共识", "人事汇集之后，以什么中心来凝聚？"],
  ["上升与积累", "今天能完成哪一小级台阶？"],
  ["困顿与守志", "资源受限时，哪些承诺仍值得坚持？"],
  ["共同水源", "制度与资源如何被持续维护并公平使用？"],
  ["变革与时机", "旧秩序已失效的证据是否足够清楚？"],
  ["鼎新与转化", "新的容器能否承载新的内容？"],
  ["震动与醒觉", "意外发生后，第一件该恢复秩序的事是什么？"],
  ["止与边界", "现在更需要行动，还是需要真正停下？"],
  ["循序渐进", "哪一步虽慢，却最符合成长的次序？"],
  ["关系与位置", "进入新关系或角色前，双方期待是否对齐？"],
  ["丰盛与盛衰", "高峰之中，怎样为变化预留余地？"],
  ["旅途与临时", "身在过渡地带，什么是可携带的原则？"],
  ["入与渗透", "柔和、持续的影响可以从哪里进入？"],
  ["喜悦与交流", "坦诚的交换怎样带来真实而非取悦式的愉悦？"],
  ["涣散与重聚", "什么隔阂需要消融，什么中心需要重建？"],
  ["节制与尺度", "规则在哪里提供自由，在哪里变成束缚？"],
  ["内在诚信", "言行与内心是否对齐？什么能建立可信度？"],
  ["小处谨慎", "大动作不合时宜时，哪件小事最关键？"],
  ["已成与防变", "看似完成之后，哪个细节最容易反复？"],
  ["未成与续行", "尚未完成并非失败，下一次校准在哪里？"],
];

export const TRIGRAMS = [
  { name: "坤", symbol: "☷", image: "地" },
  { name: "震", symbol: "☳", image: "雷" },
  { name: "坎", symbol: "☵", image: "水" },
  { name: "兑", symbol: "☱", image: "泽" },
  { name: "艮", symbol: "☶", image: "山" },
  { name: "离", symbol: "☲", image: "火" },
  { name: "巽", symbol: "☴", image: "风" },
  { name: "乾", symbol: "☰", image: "天" },
];


export { REFLECTIONS };
