export type SpreadId = "single" | "three" | "past-present-future" | "mind-heart-action" | "relationship-five" | "relationship-cross" | "relationship-bridge" | "reconciliation" | "self-love" | "career-path" | "career-cross" | "job-change" | "project-launch" | "business-five" | "money-budget" | "study-plan" | "exam-preparation" | "decision-two" | "decision-three" | "crossroads" | "obstacle-breakthrough" | "shadow-work" | "balance-five" | "new-moon" | "full-moon" | "week-ahead" | "month-ahead" | "year-wheel" | "celtic-cross" | "purpose" | "creative-spark" | "travel-transition";
export type ScenarioId = "general" | "relationship" | "career" | "decision" | "resources" | "study" | "self" | "growth" | "communication" | "transition" | "creative" | "weekly" | "monthly" | "annual" | "lunar";
export type TarotCard = {id:string;name:string;en:string;mark:string;upright:readonly string[];reversed:readonly string[];arcana:'major'|'minor';number?:number;suit?:string;rank?:string};
export type Trigram = {name:string;symbol:string;image:string};
export type Hexagram = {mask:number;number:number;name:string;theme:string;prompt:string;lower:Trigram;upper:Trigram};
export type NumberCasting = {numbers:[number,number,number]};
export type TimeCasting = {timestamp:string;timeZone:string};
export type Reading = {version:1;id:string;createdAt:string;question:string;scenario?:ScenarioId} & ({kind:'tarot';spread:SpreadId;cards:{id:string;reversed:boolean}[]} | {kind:'iching';lines:number[];method?:'coins'|'numbers'|'time';casting?:NumberCasting|TimeCasting});
export type Interpretation = {summary:string;insights:{reference:string;text:string}[];actions:string[];reflection:string};
export type Evidence = {reference:string;name:string;position:string;mark?:string;reversed?:boolean;keywords?:string[];number?:number;theme?:string;prompt?:string;english?:string;mask?:number;lower?:Trigram;upper?:Trigram};
export type Spread = {name:string;positions:readonly string[];description:string;category:string};
export type Scenario = {id:ScenarioId;name:string;description:string;prompts:readonly string[];recommendedSpreads:readonly SpreadId[]};
export type TarotGuide = TarotCard & {description:string;uprightMeaning:string;reversedMeaning:string;reflection:string;practice:string;symbolism:string;element:string};
export type HexagramGuide = Hexagram & {description:string;guidance:string;keywords:readonly string[]};
export type Tutorial = {id:string;title:string;description:string;category:'tarot'|'iching'|'practice';steps:readonly string[]};
export const TAROT_DECK:TarotCard[];
export const KING_WEN_BY_MASK:number[];
export const SPREADS:Readonly<Record<SpreadId,Spread>>;
export const SCENARIOS:readonly Scenario[];
export const TAROT_LIBRARY:readonly TarotGuide[];
export const HEXAGRAM_LIBRARY:readonly HexagramGuide[];
export const TUTORIALS:readonly Tutorial[];
export const ICHING_METHODS:readonly {id:'coins'|'numbers'|'time';name:string;description:string;rule:string}[];
export function randomInt(max:number,source?:()=>number):number;
export function drawTarot(spread?:SpreadId,allowReversed?:boolean,rng?:(max:number)=>number):{id:string;reversed:boolean}[];
export function castCoinLine(rng?:(max:number)=>number):{coins:number[];value:number};
export function castNumberLines(numbers:[number,number,number]):{method:'numbers';rule:'modern-numbers-v1';lines:number[];inputs:NumberCasting};
export function castTimeLines(timestamp:string,timeZone?:string):{method:'time';rule:'modern-solar-time-v1';lines:number[];inputs:TimeCasting};
export function getHexagram(mask:number):Hexagram;
export function validateReading(value:unknown):Reading;
export function evidenceFor(value:Reading):Evidence[];
export function basicInterpretation(value:Reading):Interpretation;
export function validateInterpretation(value:unknown,reading:Reading):Interpretation;
export function validateInterpretationForEvidence(value:unknown,evidence:Evidence[]):Interpretation;
export function readingText(value:Reading,interpretation?:Interpretation):string;
export function analyseLines(lines:number[]):{original:Hexagram;resulting:Hexagram;moving:number[];lines:number[];mutual:Hexagram;opposite:Hexagram;reversed:Hexagram};
export function dailyMessage(cardId:string):{title:string;text:string;action:string;reflection:string};
export const DAILY_MOODS:{id:string;label:string;symbol:string}[];
