import { useState,type FormEvent } from 'react';
import { useMutation,useQuery,useQueryClient,useInfiniteQuery } from '@tanstack/react-query';
import { Sparkles,RotateCcw,Shuffle,ArrowUpRight,MessageCircle,BookOpen } from 'lucide-react';
import { drawTarot,castCoinLine,castNumberLines,castTimeLines,basicInterpretation,SPREADS,SCENARIOS,type Reading,type Interpretation } from '@star-oracle/domain';
import type { ReadingRecord } from '@star-oracle/contracts';
import { useSession } from '../lib/session';
import { api,json } from '../lib/api';
import { Button,Notice,Reveal } from '../components/ui';
import { ReadingView,Hexagram } from '../components/reading';
import { Link } from 'react-router-dom';
import './divination.css';
type SpreadId=keyof typeof SPREADS;
type ScenarioId=(typeof SCENARIOS)[number]['id'];
type ConversationEntry={id:string;prompt:string;answer:Interpretation|null;status:'pending'|'done'|'failed';createdAt:string};
const spreadList=Object.entries(SPREADS) as [SpreadId,(typeof SPREADS)[SpreadId]][];
const spreadCategories=Array.from(new Set(spreadList.map(([,value])=>value.category)));
const categoryNames:Record<string,string>={general:'基础与综合',self:'自我探索',relationship:'关系与沟通',career:'事业与项目',resources:'资源与预算',study:'学习与备考',decision:'选择与决策',growth:'成长与突破',cycle:'周期与规划',transition:'转变与旅程'};
function currentShanghaiTime(){
 const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date());
 const value=(type:string)=>parts.find(p=>p.type===type)?.value??'00';
 return value('year')+'-'+value('month')+'-'+value('day')+'T'+value('hour')+':'+value('minute');
}
function Conversation({record,aiEnabled,provider}:{record:ReadingRecord;aiEnabled:boolean;provider:string}){
 const {user}=useSession(),cache=useQueryClient(),[prompt,setPrompt]=useState(''),[consent,setConsent]=useState(false),[attempt,setAttempt]=useState(()=>crypto.randomUUID());
 const key=['conversation',user?.id,record.id];
 const query=useInfiniteQuery({queryKey:key,initialPageParam:'',queryFn:({pageParam})=>api<{items:ConversationEntry[];nextCursor:string|null}>('/readings/'+record.id+'/conversation?limit=20'+(pageParam?'&cursor='+encodeURIComponent(pageParam):'')),getNextPageParam:last=>last.nextCursor??undefined,refetchInterval:query=>query.state.data?.pages.some(page=>page.items.some(item=>item.status==='pending'))?2000:false,enabled:!!user,retry:false});
 const send=useMutation({mutationFn:(requestId:string)=>api<ConversationEntry>('/readings/'+record.id+'/conversation',{method:'POST',body:json({prompt,consent:true,requestId})}),onSuccess:()=>{setPrompt('');setAttempt(crypto.randomUUID());cache.invalidateQueries({queryKey:key});}});
 function submit(e:FormEvent){e.preventDefault();const id=send.isError?crypto.randomUUID():attempt;setAttempt(id);send.mutate(id);}
 return <details className="oracle-details conversation-panel"><summary><MessageCircle size={17}/>围绕这次结果，继续聊聊</summary><p className="muted small">继续理解同一组牌或卦象，不会重新抽牌。AI 会收到本次问题、结果、本次追问和有限的最近对话；日记不会发送。模型服务：{provider}。</p>
 {!user?<p className="muted"><Link className="text-link" to="/account">登录后开启追问 <ArrowUpRight size={14}/></Link></p>:<>
 <div className="conversation-list" aria-live="polite">{query.data?.pages.flatMap(page=>page.items).map(item=><article className="conversation-entry" key={item.id}><p className="conversation-prompt"><span>你</span>{item.prompt}</p>{item.answer?<div className="conversation-answer"><span className="eyebrow">基于本次结果</span><p>{item.answer.summary}</p>{item.answer.insights.map((insight,i)=><p key={i}>{insight.text}</p>)}{item.answer.actions.length?<ul>{item.answer.actions.map((action,i)=><li key={i}>{action}</li>)}</ul>:null}<p className="reflection">{item.answer.reflection}</p></div>:<p className="muted small">{item.status==='pending'?'这次请求正在处理中，请稍后刷新。':'这次解读没有完成，你可以重新提出追问。'}</p>}</article>)}</div>{query.hasNextPage?<Button className="secondary" busy={query.isFetchingNextPage} onClick={()=>query.fetchNextPage()}>查看更多对话</Button>:null}<Notice error={query.error}/>
 <form onSubmit={submit}><label htmlFor={'follow-up-'+record.id}>你还想了解什么？</label><textarea id={'follow-up-'+record.id} value={prompt} onChange={e=>{setPrompt(e.target.value);setAttempt(crypto.randomUUID());}} minLength={2} maxLength={1000} required placeholder="例如：你提到沟通，我可以从哪一步开始？"/><span className="field-hint">{prompt.length}/1000 · 不要填写他人的隐私信息。</span><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我同意将上述问题、结果及相关对话发送给模型服务</label><Button type="submit" busy={send.isPending} disabled={!consent||!aiEnabled}>{aiEnabled?(send.isError?'重试追问':'发送追问'):'AI 暂未启用'} <Sparkles size={16}/></Button><Notice error={send.error}/></form>
 </>}</details>;
}
export function Explore({kind}:{kind:'tarot'|'iching'}){
 const {user}=useSession(),[question,setQuestion]=useState(''),[spread,setSpread]=useState<SpreadId>('three'),[scenario,setScenario]=useState<ScenarioId>('general'),[category,setCategory]=useState('all'),[reversed,setReversed]=useState(true),[result,setResult]=useState<ReadingRecord|null>(null),[revealed,setRevealed]=useState(0),[flipped,setFlipped]=useState<boolean[]>([]),[consent,setConsent]=useState(false),[attemptId,setAttemptId]=useState(()=>crypto.randomUUID()),[aiAttempt,setAiAttempt]=useState(()=>crypto.randomUUID()),[method,setMethod]=useState<'coins'|'numbers'|'time'>('coins'),[numbers,setNumbers]=useState(['7','23','41']),[time,setTime]=useState(currentShanghaiTime),[shuffle,setShuffle]=useState(0);
 const settings=useQuery({queryKey:['public-config'],queryFn:()=>api<{aiEnabled:boolean;aiProvider:string}>('/config'),staleTime:60000});
 const selectedScenario=SCENARIOS.find(item=>item.id===scenario)??SCENARIOS[0]!,selectedSpread=SPREADS[spread];
 function changed(){setAttemptId(crypto.randomUUID());}
 const draw=useMutation({mutationFn:async()=>{
  const tuple=numbers.map(value=>Number(value)) as [number,number,number];
  if(kind==='iching'&&method==='numbers'&&tuple.some(value=>!Number.isSafeInteger(value)||value<1||value>1_000_000_000))throw new Error('请输入三个 1 到 10 亿之间的正整数。');
  const timestamp=method==='time'?new Date(time+':00+08:00').toISOString():undefined;
  if(user)return api<ReadingRecord>('/readings',{method:'POST',body:json({kind,question,spread,scenario,method:kind==='iching'?method:undefined,numbers:kind==='iching'&&method==='numbers'?tuple:undefined,time:kind==='iching'&&method==='time'?timestamp:undefined,allowReversed:reversed,requestId:attemptId})});
  const base={version:1 as const,id:crypto.randomUUID(),createdAt:new Date().toISOString(),question,scenario};
  const casting=kind==='iching'&&method==='numbers'?castNumberLines(tuple):kind==='iching'&&method==='time'?castTimeLines(timestamp!):null;
  const reading:Reading=kind==='tarot'?{...base,kind,spread,cards:drawTarot(spread,reversed)}:{...base,kind,lines:casting?.lines??Array.from({length:6},()=>castCoinLine().value),method,casting:casting?.inputs};
  return {id:reading.id,reading,interpretation:basicInterpretation(reading),shared:false,ai:false,createdAt:reading.createdAt};
 },onSuccess:value=>{setResult(value);setRevealed(kind==='iching'&&method==='coins'?0:6);setFlipped(value.reading.kind==='tarot'?value.reading.cards.map(()=>false):[]);}});
 const ai=useMutation({mutationFn:(requestId:string)=>api<ReadingRecord>('/readings/'+result!.id+'/interpret',{method:'POST',body:json({consent:true,requestId})}),onSuccess:setResult});
 function submit(e:FormEvent){e.preventDefault();draw.mutate();}
 function reset(){setResult(null);changed();setConsent(false);setAiAttempt(crypto.randomUUID());setFlipped([]);draw.reset();ai.reset();}
 return <Reveal className="page narrow divination-page"><div className="oracle-heading"><span className="eyebrow">{kind==='tarot'?'TAROT / A NEW PERSPECTIVE':'I CHING / THE ART OF CHANGE'}</span><Link className="text-link" to={kind==='tarot'?'/library?tab=tarot':'/library?tab=iching'}><BookOpen size={14}/>学习图鉴</Link></div><h1>{kind==='tarot'?'给问题，另一种光。':'听见变化的节奏。'}</h1><p className="page-intro">{kind==='tarot'?'从一个具体的问题开始，选择适合此刻的牌阵。':'让问题落在生活里。用一种清楚的规则，观察守住与改变。'}</p><div className="explore-tabs" aria-label="选择占卜方式"><Link className={kind==='tarot'?'active':''} to="/tarot">塔罗 · 象征与视角</Link><Link className={kind==='iching'?'active':''} to="/iching">易经 · 变化与行动</Link></div>
 {!result?<form className="form-panel divination-form" onSubmit={submit}>
 <section aria-labelledby="scenario-title"><div className="field-heading"><span className="step-number">01</span><h2 id="scenario-title">找到你的主题</h2></div><div className="scenario-chips" aria-label="探索主题">{SCENARIOS.map(item=><button key={item.id} type="button" aria-pressed={scenario===item.id} className={scenario===item.id?'selected':''} onClick={()=>{setScenario(item.id);if(kind==='tarot'){setSpread(item.recommendedSpreads[0]??'three');setCategory('all');}changed();}}>{item.name}</button>)}</div><p className="muted small">{selectedScenario.description}</p></section>
 <section aria-label="问题与探索主题"><div className="field-heading"><span className="step-number">02</span><label id="question-label" htmlFor="question">此刻，你想探索什么？</label></div><textarea id="question" value={question} onChange={e=>{setQuestion(e.target.value);changed();}} minLength={2} maxLength={500} placeholder="例如：面对新的机会，我需要留意什么？" required/><span className="field-hint">不必填写姓名、联系方式或其他敏感信息。{question.length}/500</span><div className="question-prompts" aria-label="推荐问题">{selectedScenario.prompts.slice(0,3).map(prompt=><button type="button" key={prompt} onClick={()=>{setQuestion(prompt);changed();}}>{prompt} <ArrowUpRight size={12}/></button>)}</div></section>
 {kind==='tarot'?<section aria-labelledby="spread-title"><div className="field-heading"><span className="step-number">03</span><h2 id="spread-title">选择你的牌阵</h2></div><div className="spread-filters" aria-label="牌阵分类"><button type="button" className={category==='all'?'active':''} aria-pressed={category==='all'} onClick={()=>setCategory('all')}>全部 · {spreadList.length}</button>{spreadCategories.map(value=><button type="button" key={value} className={category===value?'active':''} aria-pressed={category===value} onClick={()=>setCategory(value)}>{categoryNames[value]??value}</button>)}</div><div className="spread-picker">{spreadList.filter(([,value])=>category==='all'||category===value.category).map(([id,value])=><button type="button" key={id} aria-pressed={spread===id} className={'spread-option '+(spread===id?'selected':'')} onClick={()=>{setSpread(id);changed();}}><span className="spread-count">{value.positions.length}</span><strong>{value.name}</strong><span className="spread-category">{categoryNames[value.category]??value.category}{selectedScenario.recommendedSpreads.includes(id)?' · 本主题推荐':''}</span></button>)}</div><div className="spread-preview" aria-live="polite"><h3>{selectedSpread.name}</h3><p>{selectedSpread.description}</p><ol>{selectedSpread.positions.map((position,i)=><li key={i}>{position}</li>)}</ol></div><label className="checkbox"><input type="checkbox" checked={reversed} onChange={e=>{setReversed(e.target.checked);changed();}}/>包含逆位 · 留意阻碍、过度与尚未表达的部分</label><div className={'shuffle-stage '+(shuffle?'has-shuffled':'')} key={shuffle} aria-hidden="true"><span/><span/><span/></div><Button type="button" className="secondary" onClick={()=>setShuffle(value=>value+1)}><Shuffle size={16}/>{shuffle?'再洗一次牌':'静心洗牌'}</Button><p className="muted small">洗牌动画是一段停顿；实际牌面由安全随机数产生，洗牌次数不影响结果。</p></section>:<section aria-labelledby="method-title"><div className="field-heading"><span className="step-number">03</span><h2 id="method-title">选择起卦规则</h2></div><div className="segmented casting-methods" aria-label="起卦方法">{[['coins','三枚硬币'],['numbers','三个数字'],['time','公历时间']].map(([id,label])=><button type="button" key={id} className={method===id?'selected':''} aria-pressed={method===id} onClick={()=>{setMethod(id as typeof method);changed();}}>{label}</button>)}</div>
 {method==='numbers'?<><div className="number-inputs">{numbers.map((value,i)=><label key={i}>第 {i+1} 个数字<input type="number" inputMode="numeric" min={1} max={1_000_000_000} step={1} required value={value} onChange={e=>{setNumbers(current=>current.map((n,j)=>j===i?e.target.value:n));changed();}}/></label>)}</div><p className="rule-note">现代数字简化法：第一、第二个数字分别按先天八卦次序取余 8 得到上卦、下卦；第三个数字取余 6 得到动爻，余 0 分别记为 8 或 6。数字由你提供。</p></>:method==='time'?<><label htmlFor="casting-time">上海时间（公历，UTC+8）</label><input id="casting-time" type="datetime-local" required min="1900-01-01T00:00" max="2100-12-31T23:59" value={time} onChange={e=>{setTime(e.target.value);changed();}}/><Button type="button" className="secondary time-refresh" onClick={()=>{setTime(currentShanghaiTime());changed();}}>更新为当前上海时间</Button><p className="rule-note">现代公历简化法：年＋月＋日取余 8 得上卦；再加时辰序数，取余 8 得下卦，取余 6 得动爻，余 0 记为 8 或 6。子时 23:00—00:59 为 1，依次到亥时 21:00—22:59 为 12；23 时仍取当日公历日期。此规则不等同传统农历梅花易数，结果保留时间来源。</p></>:<p className="rule-note">三枚硬币法：每次三枚硬币分别取 2 或 3，相加得到 6、7、8 或 9；共六次，由下而上。6 为老阴、9 为老阳，会变爻；7 与 8 为静爻。</p>}</section>}
 <div className="draw-footer"><Button busy={draw.isPending} type="submit">{kind==='tarot'?'开始抽牌':'开始起卦'} <Sparkles size={17}/></Button><span className="muted small">不预测确定的未来，给当下一个新视角。</span></div><Notice error={draw.error}/>{!user?<p className="muted small">你正在访客体验，结果不会自动上传。<Link className="text-link" to="/account">登录</Link>可保存记录与使用 AI 解读。</p>:<p className="muted small">记录默认仅你可见。共享需要你主动开启。</p>}
 </form>:<>{kind==='iching'&&revealed<6&&result.reading.kind==='iching'?<div className="ritual"><Hexagram lines={result.reading.lines} revealed={revealed}/><p>由下而上 · 第 {revealed+1} 爻</p><div className="ritual-coins" aria-hidden="true"><span/><span/><span/></div><Button onClick={()=>setRevealed(value=>value+1)}>掷三枚铜钱</Button><p className="muted small">六爻已按三枚硬币规则产生，逐次展开给此刻一个停顿。</p></div>:<>
 {result.reading.kind==='tarot'&&flipped.some(value=>!value)?<div className="reveal-toolbar"><p>按顺序翻开，或一次看见全貌。</p><Button className="secondary" onClick={()=>setFlipped(current=>current.map(()=>true))}>全部翻开</Button></div>:null}
 <ReadingView {...result} revealedCards={result.reading.kind==='tarot'?flipped:undefined} onReveal={result.reading.kind==='tarot'?index=>setFlipped(current=>current.map((value,i)=>i===index?true:value)):undefined}/>
 {user&&!result.ai?<div className="ai-panel"><h3>让解读靠近你的问题</h3><p>AI 将结合这次牌面或卦象整理建议。问题和结果会发送到 {settings.data?.aiProvider??'网站配置的模型服务'}；私人日记不会发送。</p><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我同意发送本次问题与结果进行 AI 解读</label><Button busy={ai.isPending} disabled={!consent||!settings.data?.aiEnabled} onClick={()=>{const id=ai.isError?crypto.randomUUID():aiAttempt;setAiAttempt(id);ai.mutate(id);}}>{settings.data?.aiEnabled?(ai.isError?'重试 AI 解读':'生成 AI 解读'):'AI 暂未启用'} <Sparkles size={16}/></Button><Notice error={ai.error}/></div>:null}
 <Conversation key={result.id} record={result} aiEnabled={settings.data?.aiEnabled??false} provider={settings.data?.aiProvider??'网站配置的模型服务'}/>
 <Button className="secondary" onClick={reset}>再探索一个问题 <RotateCcw size={16}/></Button></>}</>}
 </Reveal>;
}
