import {Link} from 'react-router-dom';
import {ArrowUpRight,Sunrise,Layers,Wind,BookOpen,LockKeyhole} from 'lucide-react';
import {Observatory} from '../components/observatory';
export function Home(){
 const paths=[{to:'/tarot',Icon:Layers,label:'塔罗',title:'给问题，另一种光。',text:'从 78 张牌的象征里，找到理解当下的新角度。32 种牌阵，为不同的问题留出空间。',action:'开启塔罗探索'},{to:'/iching',Icon:Wind,label:'易经',title:'听见变化的节奏。',text:'三枚硬币、三个数字，或此刻的时间。以清楚的规则起卦，观察守住与改变。',action:'开始一次起卦'},{to:'/daily',Icon:Sunrise,label:'每日星笺',title:'一张牌，一页心绪。',text:'领取今天的来信，留下一点心情。把微小的变化，写进只属于自己的日子。',action:'读今日星笺'}];
 return <><section className="luminous-hero"><div className="luminous-hero-copy"><span className="home-intro-label">照见 · 心灵天文台</span><h1>抬头看星，<br/>回身看见自己。</h1><p>让塔罗的象征、易经的变化，<br/>陪你整理此刻的心绪。</p><div className="hero-actions"><Link className="button" to="/tarot">开启一次探索 <ArrowUpRight size={17}/></Link><Link className="text-link" to="/daily">读今日星笺</Link></div><span className="hero-endnote">不预测确定的未来，给当下一个新视角。</span></div><Observatory className="home-observatory"/></section>
 <section id="paths" className="section luminous-paths"><div className="luminous-section-title"><h2>从这里，慢慢走近自己。</h2><Link className="text-link" to="/tutorials"><BookOpen size={15}/>第一次来？看看入门指引</Link></div><div className="path-grid">{paths.map(({to,Icon,label,title,text,action})=><Link className="path-card" key={to} to={to}><span className="path-label"><Icon size={21}/>{label}</span><h3>{title}</h3><p>{text}</p><span className="path-open">{action}<ArrowUpRight size={17}/></span></Link>)}</div></section>
 <section className="luminous-note"><div><span className="note-star">✧</span><h2>答案之外，<br/>还有你自己的声音。</h2></div><div><p>探索可以留下线索，日记可以安放心情。<br/>回看走过的日子，再迈出一个小小的行动。</p><Link className="text-link" to="/space">进入我的星空 <ArrowUpRight size={16}/></Link><p className="note-privacy"><LockKeyhole size={14}/>私人内容由你掌握，可以导出，也可以删除。</p><Link className="privacy-note-link" to="/privacy">了解隐私与使用说明</Link></div></section></>;
}
